config/routes.rb
Rails.application.routes.draw do
  root to: "homes#index"

  resources :asignatures, only: [:index, :new, :create, :destroy] do
    member do
      get "students"
    end
  end
  resources :teachers, only: [:index, :new, :create, :destroy] do
    member do
      get "asignatures"
    end
  end
  resources :courses, only: [:index, :new, :create, :destroy]
  resources :students, only: [:index, :new, :create, :destroy]  do
    member do
      get "new_calification"
      post "create_calification"
    end
  end


  namespace :api do
    namespace :v1 do
        resources :students, only: [:index]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asignature.rb
class Asignature < ApplicationRecord
  belongs_to :teacher
  has_many :asignature_courses, dependent: :destroy
  has_many :courses, through: :asignature_courses

  has_many :asignature_students, dependent: :destroy
  has_many :students, through: :asignature_students

  accepts_nested_attributes_for :courses, :allow_destroy => true
end

app/models/asignature_course.rb
class AsignatureCourse < ApplicationRecord
  belongs_to :course
  belongs_to :asignature
end

app/models/asignature_student.rb
class AsignatureStudent < ApplicationRecord
  belongs_to :student
  belongs_to :asignature

  validate :calification

  def calification
    data = Student.count + Time.now.strftime('%M').to_i
    if self.value > data
      errors.add(:value, "No puede superar el minuto en curso de la hora actual junto con la cantidad de estudiantes creados en la base de datos")
    end

  end

end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :teacher

  has_many :student_courses, dependent: :destroy
  has_many :students, through: :student_courses

  has_many :asignature_courses, dependent: :destroy
  has_many :asignatures, through: :asignature_courses
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :student_courses, dependent: :destroy
  has_many :courses, through: :student_courses

  has_many :asignature_students, dependent: :destroy
  has_many :asignatures, through: :asignature_students

  accepts_nested_attributes_for :asignatures, :allow_destroy => true

end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :course
  belongs_to :student
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :courses
  has_many :asignatures
end

app/controllers/api/v1/students_controller.rb
class Api::V1::StudentsController < ApiController
  def index
    @students = Student.includes(:asignature_students, :asignatures)
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  protect_from_forgery with: :null_session


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/asignatures_controller.rb
class AsignaturesController < ApplicationController
  def index
    @asignatures = Asignature.all
  end

  def students
    asignature = Asignature.find params[:id]
    @students = asignature.students

    render "students/index"
  end

  def new
    @asignature = Asignature.new
  end

  def create
    @asignature = Asignature.new permit_parmas
    if @asignature.save
      redirect_to asignatures_path(@asignature), notice: "Registro creado correctamente."
    else
      render :new
    end
  end

  def destroy
    @asignature = Asignature.find params[:id]
    if @asignature.destroy
      redirect_to asignatures_path(@asignature), notice: "Registro eliminado correctamente."
    else
      redirect_to asignatures_path(@aasignature), notice: "Registro NO eliminado."
    end
  end

  private
  def permit_parmas
    params.require(:asignature).permit(:name, :teacher_id, course_ids: [])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new permit_parmas
    if @course.save
      redirect_to courses_path(@course), notice: "Registro creado correctamente."
    else
      render :new
    end
  end

  def destroy
    @course = Course.find params[:id]
    if @course.destroy
      redirect_to courses_path(@course), notice: "Registro eliminado correctamente."
    else
      redirect_to courses_path(@acourse), notice: "Registro NO eliminado."
    end
  end

  private
  def permit_parmas
    params.require(:course).permit(:name, :teacher_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def new_calification
    @asignature_student = AsignatureStudent.find(params[:id])
  end
  def create_calification
    @asignature_student = AsignatureStudent.find(params[:id])
    @asignature_student.update(value: params[:student][:value])
    if @asignature_student.save
      students_asignature_path(@asignature_student.asignature_id)
      redirect_to students_asignature_path(@asignature_student.asignature_id)
    else
      render "new_calification", error: "Error: #{@asignature_student.errors.full_messages.to_sentence}"
    end

  end

  def create
    @student = Student.new permit_parmas
    if @student.save
      redirect_to students_path(@student), notice: "Registro creado correctamente."
    else
      puts "===errors=> #{@student.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def destroy
    @student = Student.find params[:id]
    if @student.destroy
      redirect_to students_path(@student), notice: "Registro eliminado correctamente."
    else
      redirect_to students_path(@astudent), notice: "Registro NO eliminado."
    end
  end

  private
  def permit_parmas
    # params.require(:student).permit(:name, asignature_ids: []) if create_calification != "create_calification"

    # if create_calification == "create_calification"
    #   params.require(:asignature_students).permit(:id, :value)
    # else
      params.require(:student).permit(:name, asignature_ids: [], asignature_students_attribute: [:id, :value])
    # end
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.all
  end

  def asignatures
    teacher = Teacher.find params[:id]
    @asignatures = teacher.asignatures

    render "asignatures/index"
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new permit_parmas
    if @teacher.save
      redirect_to teachers_path(@teacher), notice: "Registro creado correctamente."
    else
      render :new
    end
  end

  def destroy
    @teacher = Teacher.find params[:id]
    if @teacher.destroy
      redirect_to teachers_path(@teacher), notice: "Registro eliminado correctamente."
    else
      redirect_to teachers_path(@ateacher), notice: "Registro NO eliminado."
    end
  end

  private
  def permit_parmas
    params.require(:teacher).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asignatures_helper.rb
module AsignaturesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/asignatures/index.html.erb
<div class="container">

<h1>Lista de asignaturas</h1>

<%= link_to "HOME", root_path %>
<br>
<%= link_to "Crear", new_asignature_path %>

<br>
<br>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Docente</th>
      <th scope="col">Cursos</th>
      <th scope="col">Acción</th>
    </tr>
  </thead>
  <tbody>
    <% @asignatures.each do |asignature| %>
    <tr>
      <th scope="row"><%= asignature.id %></th>
      <td><%= asignature.name %></td>
      <td><%= asignature.teacher_id.blank? ? "no asignado" : asignature.teacher.name %></td>
      <td>
        <% asignature.courses.each do |course| %>
        <p>
          <%= course.name %>
        </p>
        <% end %>
      </td>
      <td>
        <%= link_to "Ver estudiantes", students_asignature_path(asignature) %>
        <br>
        <%= link_to "Eliminar", asignature_path(asignature), method: :delete, data: {confirm: "¿Estas seguro?"} %></td>
    </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/asignatures/new.html.erb
<div class="container">
  <%= form_for(@asignature) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name,  class: "form-control", id: "name", placeholder: "Enter Name" %>
    </div>

    <div class="col-md-12 margin-bottom15">
      <label class="label-form-profile">Docente</label></label>
      <%= f.select :teacher_id, Teacher.all.collect {|a| [a.name, a.id]}, {}, class: "form-control" %>
    </div>

    <div class="col-md-12 form-group">
      <label class="label-form-profile">Cursos </label>
      <%=  f.collection_check_boxes :course_ids, Course.all, :id, :name do |b|  %>
      <div class="collection-check-box">
        <%= b.check_box %>
        <%= b.label %>
      </div>
      <% end %>
    </div>


    <%= f.submit "Guardar", class: "btn btn-primary" %>
    <br>
    <%= link_to "Regresar", asignatures_path, class: "btn btn-default " %>
  <% end %>
</div>

app/views/courses/index.html.erb
<div class="container">

<h1>Lista de Cursos</h1>

<%= link_to "HOME", root_path %>
<br>
<%= link_to "Crear", new_course_path %>

<br>
<br>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Docente</th>
      <th scope="col">Acción</th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
    <tr>
      <th scope="row"><%= course.id %></th>
      <td><%= course.name %></td>
      <td><%= course.teacher_id.blank? ? "no asignado" : course.teacher.name.to_s %></td>
      <td>
        <%= link_to "Eliminar", course_path(course), method: :delete, data: {confirm: "¿Estas seguro?"} %></td>
    </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/courses/new.html.erb
<div class="container">
  <%= form_for(@course) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name,  class: "form-control", id: "name", placeholder: "Enter Name" %>
    </div>

    <div class="col-md-12 margin-bottom15">
      <label class="label-form-profile">Docente</label></label>
      <%= f.select :teacher_id, Teacher.all.collect {|a| [a.name, a.id]}, {}, class: "form-control" %>
    </div>

    <%= f.submit "Guardar", class: "btn btn-primary" %>
    <br>
    <%= link_to "Regresar", courses_path, class: "btn btn-default " %>
  <% end %>
</div>

app/views/homes/index.html.erb
<div class="container">

  <h1>Sistema de calificaciones</h1>
  <br>
  <br>
  <%= link_to "Asignaturas", asignatures_path %>
  <br>
  <br>
  <%= link_to "Profesores", teachers_path %>
  <br>
  <br>
  <%= link_to "Estudiantes", students_path %>
  <br>
  <br>
  <%= link_to "Cursos", courses_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<div class="container">

<h1>Lista de Estudiantes</h1>

<%= link_to "HOME", root_path %>
<br>
<%= link_to "Crear", new_student_path %>

<br>
<br>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Asignaturas</th>
      <th scope="col">Acción</th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
    <tr>
      <th scope="row"><%= student.id %></th>
      <td><%= student.name %></td>
      <td>
        <% student.asignature_students.each do |as| %>
          <p>
            <%= as.asignature.name %>
            <span> | </span>
            Calificación: <%= as.value %>
            <span> | </span>
            <%= link_to "Calificar", new_calification_student_path(as.id) %>
          </p>
        <% end %>
      </td>
      <td>
        <%= link_to "Eliminar", student_path(student), method: :delete, data: {confirm: "¿Estas seguro?"} %></td>
    </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/students/new.html.erb
<div class="container">
  <%= form_for(@student) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name,  class: "form-control", id: "name", placeholder: "Enter Name" %>
    </div>

    <div class="col-md-12 form-group">
      <label class="label-form-profile">Matricular en: </label>
      <%=  f.collection_check_boxes :asignature_ids, Asignature.all, :id, :name do |b|  %>
      <div class="collection-check-box">
        <%= b.check_box %>
        <%= b.label %>
      </div>
      <% end %>
    </div>

    <%= f.submit "Guardar", class: "btn btn-primary" %>
    <br>
    <%= link_to "Regresar", students_path, class: "btn btn-default " %>
  <% end %>
</div>

app/views/students/new_calification.html.erb
<div class="container">
  <%= form_for(@asignature_student, as: :student, url: create_calification_student_path(@asignature_student), method: :post) do |f| %>
  <% if @asignature_student.errors.any? %>
    <% @asignature_student.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end  %>
  <% end  %>
    <div class="form-group">
      <%= f.label :value %>
      <%= f.text_field :value,  class: "form-control", id: "value", placeholder: "Enter Nota" %>
    </div>

    <%= f.submit "Guardar", class: "btn btn-primary" %>
    <br>

    <%= link_to "Regresar", students_asignature_path(@asignature_student.asignature_id), class: "btn btn-default " %>
  <% end %>
</div>

app/views/teachers/index.html.erb
<div class="container">

<h1>Lista de Profesores</h1>

<%= link_to "HOME", root_path %>
<br>
<%= link_to "Crear", new_teacher_path %>

<br>
<br>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Acción</th>
    </tr>
  </thead>
  <tbody>
    <% @teachers.each do |teacher| %>
    <tr>
      <th scope="row"><%= teacher.id %></th>
      <td><%= teacher.name %></td>
      <td>
        <%= link_to "Ver asignaturas", asignatures_teacher_path(teacher) %>
        <br>
        <%= link_to "Eliminar", teacher_path(teacher), method: :delete, data: {confirm: "¿Estas seguro?"} %></td>
    </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/teachers/new.html.erb
<div class="container">
  <%= form_for(@teacher) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name,  class: "form-control", id: "name", placeholder: "Enter Name" %>
    </div>
    <%= f.submit "Guardar", class: "btn btn-primary" %>
    <br>
    <%= link_to "Regresar", teachers_path, class: "btn btn-default " %>
  <% end %>
</div>